name: subscription_tracker
description: "Premium subscription tracking app with soft UI design."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  
  # UI & Fonts
  google_fonts: ^6.2.1
  
  # Auth & Security
  local_auth: ^2.3.0
  crypto: ^3.0.3
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/
